namespace:
  name: sandbox

image:
  repository: sitgesfer/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
