namespace:
  name: prod

image:
  repository: sitgesfer/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

containerPort: 3111

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
